library(dplyr)
library(lubridate)
png(filename="plot4.png",width=480,height=480,units="px")
uci<-read.table("./household_power_consumption.txt", sep = ";", header = TRUE)
uci<-mutate(uci,Date = dmy(Date))
uciNew<-subset(uci, Date>= "2007-02-01" & Date <= "2007-02-02")
Date_time<-strptime(paste(uciNew$Date,uciNew$Time),format = "%Y-%m-%d %H:%M:%S")
uciNew2<-cbind(uciNew,Date_time)
uciNew2<-mutate(uciNew2,Global_active_power = as.numeric(as.character(uciNew2$Global_active_power)), Global_reactive_power = as.numeric(as.character(uciNew2$Global_reactive_power)))
par(mfrow=c(2,2))
with(uciNew2,plot(Date_time,Global_active_power, type = "l", xlab = "",ylab = "Global Active Power (kilowatts)"))
with(uciNew2,plot(Date_time,Voltage,type = "l",xlab = "datetime",ylab = "Voltage"))
plot(uciNew2$Date_time,uciNew2$Sub_metering_1,xlab = "",ylab = "Energy sub metering",type = "l")
lines(uciNew2$Date_time,uciNew2$Sub_metering_2,col = "red")
lines(uciNew2$Date_time,uciNew2$Sub_metering_3,col = "blue")
legend("topright",legend = c("Sub_meterin_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = "solid")
with(uciNew2,plot(Date_time,Global_reactive_power,xlab = "datetime",ylab = "Global_reactive_power", type = "l" ))
dev.off()
