library(dplyr)
library(lubridate)
png(filename='plot3.png', width=480, height=480, units='px')
uci<-read.table("./household_power_consumption.txt", sep = ";", header = TRUE)
uci<-mutate(uci,Date = dmy(Date))
uciNew<-subset(uci, Date>= "2007-02-01" & Date <= "2007-02-02")
Date_time<-strptime(paste(uciNew$Date,uciNew$Time),format = "%Y-%m-%d %H:%M:%S")
uciNew<-cbind(uciNew,Date_time)
uciNew2<-select(uciNew,-c(Date:Time))
plot(uciNew2$Date_time,uciNew2$Sub_metering_1,type = "l",xlab="",ylab = "Energy sub metering")
lines(uciNew2$Date_time,uciNew2$Sub_metering_2, col = "red")
lines(uciNew2$Date_time,uciNew2$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"),lty = "solid")
dev.off()
