library(dplyr)
library(lubridate)
png(filename='plot2.png', width=480, height=480, units='px')
uci<-read.table("./household_power_consumption.txt",sep = ";", header = TRUE)
uci<-mutate(uci,Date = dmy(Date))
uciNew<-subset(uci, Date>= "2007-02-01" & Date <= "2007-02-02")
Date_time<-strptime(paste(uciNew$Date,uciNew$Time),format = "%Y-%m-%d %H:%M:%S")
uciNew<-cbind(uciNew,Date_time)
uciNew2<-select(uciNew,-c(Date:Time))
uciNew2<-mutate(uciNew,Global_active_power = as.numeric(as.character(uciNew$Global_active_power)))
with(uciNew2,plot(Date_time,Global_active_power,xlab="",ylab="Global Active Power (kilowatts)", type = "l"))
dev.off()
