library(dplyr)
library(lubridate)
png(filename='plot1.png', width=480, height=480, units='px')
uci<-read.table("./household_power_consumption.txt", sep  = ";", header = TRUE)
uci<-mutate(uci,Date = dmy(uci$Date))
uciNew<-subset(uci,Date>="2007-02-01" & Date<="2007-02-02")
uciNew2<-mutate(uciNew,Global_active_power = as.numeric(as.character(uciNew$Global_active_power)))
hist(uciNew2$Global_active_power,xlab = "Global Active Power (kilowatts)", main = "Global Active Power", col = "red")
dev.off()
